#!/usr/bin/env bash

# Get the list of sinks and their descriptions
SINK_LIST=$(pactl list sinks | grep "Description:" | cut -d: -f2 | sed 's/^ *//')
DIR="$HOME/.config/bspwm"
STYLE="soshi-bspwm"
RASI="$DIR/themes/$STYLE/rofi/themes.rasi"

# Use Rofi to let the user choose a sink
SELECTED_SINK=$(echo "$SINK_LIST" | rofi -dmenu -theme ${RASI} -i -p "Select Audio Output:")

echo "Selected Sink: $SELECTED_SINK"
# If a sink was selected, get its index and set it as the default sink
if [ -n "$SELECTED_SINK" ]; then
  SINK_INDEX=$(pactl list sinks | grep -B 3 "Description: $SELECTED_SINK" | grep "Sink #" | awk '{print $2}' | tr -d '#')
  echo $SINK_INDEX
  if [ -n "$SINK_INDEX" ]; then
    pactl set-default-sink "$SINK_INDEX"
    # Optional: Display a notification to confirm the change
    notify-send "Audio Output Changed" "Default audio device set to: $SELECTED_SINK"
  fi
fi
