#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# fix padding
bspc config bottom_padding 0
bspc config top_padding 0

# launch polybar
bash "$HOME/.config/polybar/polybar.sh"
