#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
STYLE="soshi-bspwm"
RASI="$HOME/.config/rofi/runner.rasi"
# Run
rofi \
  -show run \
  -theme ${RASI}
