#! /bin/sh
bspc monitor DP-0 -n monitor0 -d I II III 
bspc monitor HDMI-0 -d IV V 
bspc monitor -f ^1

bspc config border_width         2
bspc config window_gap           8
bspc config focused_border_color "#940AA1"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# scratchpad/dropdown terminal
alacritty -t scratchpad -d 0 0 &
pkill sxhkd
sxhkd &
pkill polybar
polybar &
nitrogen --restore &
pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &
pkill conky
conky &
